### ISSUE TITLE
A way to run with npx

### ISSUE THREAD

**Issue by minht11** [filipsobol/sonda#14]
[vite-bundle-visualizer](https://github.com/KusStar/vite-bundle-visualizer) has way to generate data without needing to add plugin to config file like this: `npx vite-bundle-visualizer` it would be cool if similar command was available here so it auto injects itself and executes build to generate build info.

**Comment by filipsobol** [comment]
This is the direct quote from that library that I agree with:

> In most scenarios you shouldn't need this library, the recommended solution is to add rollup-plugin-visualizer directly to your vite configuration

IMO such a command is a low-value feature, especially if it has to be done for all supported bundlers (Vite, Rollup, esbuild, webpack, Rspack) and the time will be better spent on other features.
