### ISSUE TITLE
dosent work with nextjs

### ISSUE THREAD

**Issue by 214531562** [filipsobol/sonda#42]
dosent work with nextjs

**Comment by filipsobol** [comment]
I will look into it the following days. Could you share a reproduction (for example using https://stackblitz.com/) which I can use?

**Comment by filipsobol** [comment]
Here's the configuration that worked for me in a fresh Next.js application:

```ts
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  productionBrowserSourceMaps: true,
  webpack: ( config, options ) => {
    const { SondaWebpackPlugin } = require( 'sonda' );

    if ( options.isServer ) {
      config.devtool = 'source-map';
    }

    config.plugins.push(
      new SondaWebpackPlugin( {
        filename: options.nextRuntime
          ? `sonda-report-runtime-${ options.nextRuntime }.html`
          : 'sonda-report-client.html',
      } )
    );

    return config;
  },
};

module.exports = nextConfig;
```

Running `npm run build` with this configuration creates 3 reports:

* `sonda-report-client.html`
* `sonda-report-runtime-edge.html`
* `sonda-report-runtime-nodejs.html`

The `client` and `runtime-nodejs` reports look fine, but the `runtime-edge` is empty for some reason. It also seems that the [`detailed` option](https://sonda.dev/configuration.html#detailed) doesn't work.

I will fix these issues and create a Next.js plugin to make using Sonda with it much easier, but until then, you can use the configuration from above.

**Comment by filipsobol** [comment]
Sonda `0.7.0` is out with Next.js integration. Please refer to the documentation for more details: https://sonda.dev/frameworks/nextjs.html
