### ISSUE TITLE
Support for Angular applications?

### ISSUE THREAD

**Issue by NateRadebaugh** [filipsobol/sonda#48]
I can generate an angular build with sourcemaps using [the Angular CLI](https://angular.dev/reference/configs/workspace-config#source-map-configuration) like this:
```sh
npm run ng -- build --source-map=true --verbose --named-chunks
```

This gives some chunks that I can pass into `source-map-explorer` via CLI as:
```sh
npx source-map-explorer XXX
```

From what I've seen, Sonda seems to be more full-featured than `source-map-explorer` so I'd love to switch if supported.

**Comment by NateRadebaugh** [comment]
Yes I'd happily test it. Thanks for the quick response!

**Comment by filipsobol** [comment]
It's done! In the comments of this PR, you can find both the preview npm package and the docs: https://github.com/filipsobol/sonda/pull/49.

I'd like to know two things:

1. If the integration works as expected.
2. If you prefer the JavaScript API or the CLI (both are described in the docs).

So far, all integrations / plugins have used the JavaScript API, and I'm a bit hesitant to release a CLI option only for one integration.

**Comment by NateRadebaugh** [comment]
Thanks @filipsobol this is great! The docs seem complete but unfortunately when I run it, I get no output and nothing ends up happening. I'm not sure if there's a way to enable debugging or make it more verbose, but I don't have any indication of what's going wrong.

I've tried both with and without localization enabled in my angular app.

Here's a branch/repo I'm using to test:
> https://github.com/NateRadebaugh/angular-latest/pull/31/files

I've tried both options:
1. `npm run build-with-maps`
2. `npm run run-sonda` OR `npm run analyze`

Note: I'm using M1 mac if that makes a difference.

**Comment by filipsobol** [comment]
The repo you linked to is private.

Can you check if `node_modules/sonda/bin/sonda-angular.js` starts with `#!/usr/bin/env node`? The first release didn't have it. If it doesn't, try reinstalling the dependencies and try again.

I will enable some debugging if this is not the issue.

**Comment by NateRadebaugh** [comment]
Yes I've confirmed it does start with that.

I've made that repo public so that link should work for you to see what I'm doing wrong.


I'm updating the config via the CLI, but looks like it's generating maps and `stats.json` correctly:
<img width="304" alt="image" src="https://github.com/user-attachments/assets/d421d2fc-da5b-468b-93d9-d185f7b14573" />


`package.json`
```json
"scripts": {
    "build-with-maps": "ng build --source-map=true --verbose --named-chunks --stats-json=true",
    "run-sonda": "node sonda.mjs",
    "analyze": "sonda-angular"
  },
```

`sonda.mjs`
```js
import Sonda from 'sonda/angular';

Sonda();
```

**Comment by filipsobol** [comment]
Please reinstall the dependencies and try again. I assumed that some options will be available in `angular.json`, but you enabled them via CLI.

That's why testing is important 😄

**Comment by NateRadebaugh** [comment]
Thanks, this one did fix my issue with the simple use case, but in my advanced use case using angular localization, which puts each language in its own folder, it is showing:

<img width="627" alt="image" src="https://github.com/user-attachments/assets/3600a13d-0f63-4e63-a6a8-117b22771d6c" />

I've [updated the PR](https://github.com/NateRadebaugh/angular-latest/pull/31/files) to include localization setup example. The `stats.json` location is unchanged, but each set of source maps is in a locale-specific dir:

<img width="305" alt="image" src="https://github.com/user-attachments/assets/8e6b9360-5dae-41dd-9b90-9eb706fb8bef" />

**Comment by NateRadebaugh** [comment]
One other interesting analysis I'm relying on in my current flow is to differentiate between the "initial bundle" vs lazy bundles. Right now, I have a script that's parsing the output of the main build for start/stop lines between `"initial chunk files"` and `"lazy chunk files"` to group/analyze all of these chunks together (ignoring non-initial chunks). There's no naming convention in latest angular CLI bundle outputs, so this is the only way I could get by.

Here's the script I'm currently using:
```js
const { spawn } = require("child_process");
const readline = require("readline");

let chunks = [];
let readChunks = false;

const build = spawn(
  "npm run ng -- build --source-map=true --verbose --named-chunks --stats-json=true",
  {
    shell: true,
    env: {
      ...process.env, // Spread the existing environment variables
      FORCE_COLOR: true,
    },
  }
);

build.stdout.on("data", (data) => {
  process.stdout.write(data);

  if (data.toString().includes("Application bundle generation failed")) {
    console.error(
      "\x1b[31m",
      "ERROR: Bundle generation failed. Skipping analysis.",
      "\x1b[0m"
    );
    process.exit(1);
  }
});

build.stderr.on("data", (data) => {
  process.stderr.write(data);

  if (data.toString().includes("Application bundle generation failed")) {
    console.error(
      "\x1b[31m",
      "ERROR: Bundle generation failed. Skipping analysis.",
      "\x1b[0m"
    );
    process.exit(1);
  }
});

readline
  .createInterface({
    input: build.stdout,
    terminal: false,
  })
  .on("line", (line) => {
    const lcLine = line.toLowerCase();
    if (lcLine.includes("initial chunk files")) {
      readChunks = true;
    } else if (lcLine.includes("lazy chunk files")) {
      readChunks = false;
    } else if (readChunks) {
      const mainMatch = line.match(/(main-.*\.js)/);
      if (mainMatch) {
        chunks.push(mainMatch[1]);
      }

      const chunkMatch = line.match(/(chunk-.*\.js)/);
      if (chunkMatch) {
        chunks.push(chunkMatch[1]);
      }
    }
  });

build.on("close", () => {
  let chunkPaths = "";
  chunks.forEach((chunk) => {
    chunkPaths += "./dist/browser/en/" + chunk + " ";
  });

  process.stdout.write("Chunk Paths: " + chunkPaths + "\n");
  const explorer = spawn("npx source-map-explorer " + chunkPaths, {
    shell: true,
    env: {
      ...process.env, // Spread the existing environment variables
      FORCE_COLOR: true,
    },
  });

  explorer.stdout.on("data", (data) => {
    process.stdout.write(data);
  });

  explorer.stderr.on("data", (data) => {
    process.stderr.write(data);
  });
});
```

**Comment by filipsobol** [comment]
Please reinstall the dependencies and check again. Unfortunately, Angular does not update the paths in the esbuild metafile, so they need to be fixed (made relative to cwd like all other paths) before proceeding.

**Comment by NateRadebaugh** [comment]
Thanks, I've confirmed this is now working with localized builds in angular.

In my use advanced case for a large angular application, the dropdown is huge and not entirely ussable, but I'd consider the initial integration with angular working. Thank you!!

<img width="337" alt="image" src="https://github.com/user-attachments/assets/6240b289-39f4-49be-85f4-5758a5e25cd6" />

**Comment by filipsobol** [comment]
I'm working on a major UI rework, so I'll take that into account. The current UI was created when I wanted Sonda to be mainly for library authors (where the number of bundles is small), but this has changed recently.

Going back to my original question before releasing the integration — **Do you prefer the JavaScript API or the CLI?**

**Comment by NateRadebaugh** [comment]
If all other usage is via js API then I can understand not shipping the new CLI, but if the goal is to support application developers who may be more comfortable with config-less CLI integrations with npx I could see others benefitting from CLI integration, as the "go to" replacement for source-map-explorer.

Personally I'm happy to work within the JS-only API to keep your library scope smaller.

**Comment by filipsobol** [comment]
Version `0.7.1` is out with the Angular integration. The docs are available here: https://sonda.dev/frameworks/angular-cli.html.

I decided to keep both integration options.
